# -*- coding: utf-8 -*-
"""AlphaBetaPruning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tBUTbaG5hJ9icJHHC6DxrSQctPstDEr
"""

import math

# Alpha-Beta Pruning Algorithm
def alpha_beta(depth, node_index, is_maximizing, values, alpha, beta):
    # Base case: leaf node reached
    if depth == 3:
        return values[node_index]

    if is_maximizing:
        best = -math.inf
        # Explore 2 children for each node
        for i in range(2):
            val = alpha_beta(depth + 1, node_index * 2 + i, False, values, alpha, beta)
            best = max(best, val)
            alpha = max(alpha, best)
            # Beta cut-off
            if beta <= alpha:
                print(f"Pruning at depth {depth} for node {node_index} (alpha={alpha}, beta={beta})")
                break
        return best
    else:
        best = math.inf
        for i in range(2):
            val = alpha_beta(depth + 1, node_index * 2 + i, True, values, alpha, beta)
            best = min(best, val)
            beta = min(beta, best)
            # Alpha cut-off
            if beta <= alpha:
                print(f"Pruning at depth {depth} for node {node_index} (alpha={alpha}, beta={beta})")
                break
        return best

# The leaf values for our tree (D, E, F, G)
values = [3, 5, 6, 9, 1, 2, 0, -1]

print("Leaf nodes:", values)
optimal_value = alpha_beta(0, 0, True, values, -math.inf, math.inf)
print("\nOptimal value for the root node (A):", optimal_value)